### ISSUE TITLE
Call for Draft 03 Prototype Testing

### ISSUE THREAD

**Issue by kyzer-davis** [uuid6/prototypes#21]
@jdknezek, @Daegalus, @chrylis, @mikemix, @kurttheviking, @sprql, @kjmph, @MatrixAI, @kripod, @karwa, @mareek, @oittaa, @jakwings, @fabiolimace, @LiosK, @theckman 

# Draft 03 Announcement
- Draft 03 has been submitted to the IETF!
- Draft 03 has some changes to UUIDv7 which may break current Draft 01/02 implementations so please confirm compatibility with Draft 03.
- If there is any feedback found during review or while updating the prototype implementation; please contribute to one of the existing [Discussion Threads](https://github.com/uuid6/uuid6-ietf-draft/issues?q=is%3Aissue+is%3Aopen+label%3ADiscussion) (where possible.)
- Else please open a PR to update the table in this document to reflect Draft 03 compatibility.
---

The Official Draft 03 can be found at the following locations:
- [HTML Draft 03](https://www.ietf.org/archive/id/draft-peabody-dispatch-new-uuid-format-03.html)
- [Plaintext Draft 03](https://www.ietf.org/archive/id/draft-peabody-dispatch-new-uuid-format-03.txt)
- [HTML Text](https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format-03)

---

Thanks all!

**Comment by oittaa** [comment]
Thanks for pushing this forward. I've also updated my test libraries [oittaa/uuid-php](https://github.com/oittaa/uuid-php) and [oittaa/uuid6-python](https://github.com/oittaa/uuid6-python).

**Comment by Daegalus** [comment]
thx for the heads up, might take me a bit to update, but ill get to it soon.

**Comment by Daegalus** [comment]
I just pushed up changes to catch me up to Draft 3, and added a UUIDv8, opened a PR with the changes.

**Comment by kjmph** [comment]
I updated my public [gist](https://gist.github.com/kjmph/5bd772b2c2df145aa645b837da7eca74); note, as I was used to microsecond precision, I also added UUID v8 for those looking to preserve that capability.
