### ISSUE TITLE
Call for Draft 04 Prototyping and Updates

### ISSUE THREAD

**Issue by kyzer-davis** [uuid6/prototypes#31]
Hello again!

# Draft 04 Announcement
- Draft 04 was submitted to the IETF 23 June 2022.
- Since the doc was not a major rewrite the side-by-side diff is the best place to start: [Draft 03 vs Draft 04 Diff](https://www.ietf.org/rfcdiff?url2=draft-peabody-dispatch-new-uuid-format-04)

**Full Docs**
- [HTML Draft](https://www.ietf.org/archive/id/draft-peabody-dispatch-new-uuid-format-04.html)
- [Plaintext Draft](https://www.ietf.org/archive/id/draft-peabody-dispatch-new-uuid-format-04.txt)
- [HTML Text](https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format-04)

---
If there is any feedback found during review or while updating the prototype implementation; please contribute to one of the existing [Discussion Threads](https://github.com/uuid6/uuid6-ietf-draft/issues?q=is%3Aissue+is%3Aopen+label%3ADiscussion) (where possible.)
Else please open a PR to update the table in this document to reflect Draft 04 compatibility.

Thanks All!

---

CC: @jdknezek, @Daegalus, @chrylis, @mikemix, @kurttheviking, @sprql, @kjmph, @MatrixAI, @kripod, @karwa, @mareek, @oittaa, @jakwings, @fabiolimace, @LiosK, @theckman @kjmph @iology @BaerMitUmlaut

**Comment by oittaa** [comment]
Cheers! I just updated my [Python](https://github.com/oittaa/uuid6-python) and [PHP](https://github.com/oittaa/uuid-php) libraries with the new test vectors.

**Comment by chrylis** [comment]
My library doesn't support UUIDv7 because I'm not generating anything, simply reformatting existing v1s, but if this RFC is adopted I'll go back and rewrite to support all the new ones including my methods that convert Java `Instant` to and from boundary UUIDs.

**Comment by kyzer-davis** [comment]
> My library doesn't support UUIDv7 because I'm not generating anything, simply reformatting existing v1s, but if this RFC is adopted I'll go back and rewrite to support all the new ones including my methods that convert Java `Instant` to and from boundary UUIDs.

Understood, your library should be good since it is v6 only. 
My ask: Just update the README on your repo to point to Draft 04 and I can update the table here!

**Comment by Daegalus** [comment]
I looked through the changes, I don't think there is anything for me to do on the Dart implementation, so my library is Draft 4 ready without any changes.

**Comment by chrylis** [comment]
Documentation updated: https://github.com/chrylis/time-based-uuid-reordering
