### ISSUE TITLE
Call for draft-ietf-uuidrev-rfc4122bis-03 prototypes

### ISSUE THREAD

**Issue by kyzer-davis** [uuid6/prototypes#42]
Hello again!

It has been a minute since I sent one of these! 
I just posted `draft draft-ietf-uuidrev-rfc4122bis-03` to the IETF.

What's changed since draft-peabody-dispatch-new-uuid-format-04?
- The majority of draft 00 through 02 was either:
   - Work to merge the text of RFC4122 into the original draft-peabody-dispatch-new-uuid-format-04's table of contents
   - Work to iron out problems, inconsistencies, and errors from RFC4122 versions 1 through 5 and Nil
    - As a result v1-5 now have new text and diagrams that help implementors (e.g. removed the old "everything ties back to UUIDv1 format" problem)
- The full changelog can be found below:
  - https://www.ietf.org/archive/id/draft-ietf-uuidrev-rfc4122bis-03.html#name-changelog

Items that need some feedback/testing/prototype which are "new" in the IETF drafts.
- Hashspaces! A method of bringing newer namespace UUIDs based on modern hashing protocols to UUID Version 8.
- Method 3 and 4 Monotonicity of UUIDv7
- We now have test vectors for all UUIDs (except v2), if anybody could sanity check my work that would be fantastic! 

Otherwise v6, v7, v8 should be more or less the same from a technical perspective but by all means please check compatibility and open a PR to update your library. If possible also link the version of the draft you support in your Repos README (this helps future me check these manually.)

---

### Full Docs
```
Name:		draft-ietf-uuidrev-rfc4122bis
Revision:	03
Title:		Universally Unique IDentifiers (UUID)
Document date:	2023-04-12
Group:		uuidrev
Pages:		48
URL:            https://www.ietf.org/archive/id/draft-ietf-uuidrev-rfc4122bis-03.txt
Status:         https://datatracker.ietf.org/doc/draft-ietf-uuidrev-rfc4122bis/
Html:           https://www.ietf.org/archive/id/draft-ietf-uuidrev-rfc4122bis-03.html
Htmlized:       https://datatracker.ietf.org/doc/html/draft-ietf-uuidrev-rfc4122bis
Diff:           https://author-tools.ietf.org/iddiff?url2=draft-ietf-uuidrev-rfc4122bis-03
```

---
If there is any feedback found during review or while updating the prototype implementation; please contribute to:
- The Mailer: uuidrev@ietf.org ([signup required to post](https://www.ietf.org/mailman/listinfo/uuidrev))
- IETF Github: https://github.com/ietf-wg-uuidrev/rfc4122bis/issues

Thanks All!

---

CC: @jdknezek, @Daegalus, @chrylis, @mikemix, @kurttheviking, @sprql, @kjmph, @MatrixAI, @kripod, @karwa, @mareek, @oittaa, @jakwings, @fabiolimace, @LiosK, @theckman @kjmph @iology @BaerMitUmlaut @DianaNites @jakwings @medo64 @nicolas-grekas @mlhamel

**Comment by tgross35** [comment]
Is there anywhere to find an outline for what the upcoming steps are, or a rough estimate of when the draft is expected to be accepted? It seems like it is getting close, but I'm not familiar with what makes the draft->official transition actually happen.

**Comment by tgross35** [comment]
Thank you for the details! I have been keeping up with the mailer, but I wasn't sure what point of the process it represented. Looking forward to this becoming official, thanks for all the work you've done 👍

**Comment by kyzer-davis** [comment]
### interim-2023-uuidrev-03 2023-05-10 Update:
`draft-ietf-uuidrev-rfc4122bis-03` has entered Working Group Last Call!
Please comment on the tracker or email thread before June 9th to request any changes.

The Mailer: [uuidrev@ietf.org](mailto:uuidrev@ietf.org) ([signup required to post](https://www.ietf.org/mailman/listinfo/uuidrev))
IETF Github: https://github.com/ietf-wg-uuidrev/rfc4122bis/issues
